ProjetoLuz/ContaWeb/Models/ErrorViewModel.cs
using System;

namespace ContaWeb.Models
{
    public class ErrorViewModel
    {
        public string RequestId { get; set; }

        public bool ShowRequestId => !string.IsNullOrEmpty(RequestId);
    }
}

ProjetoLuz/ContaWeb/Controllers/ContaController.cs
using ContaDomain.Entities;
using ContaRepository.Interfaces;
using ContaRepository.Repository;
using Microsoft.AspNetCore.Mvc;

namespace ContaWeb.Controllers
{
  public class ContaController : Controller
    {
        
        private IContaRepository repository;

        private IImovelRepository repositoryImovel;

        public ContaController(IContaRepository repository, IImovelRepository repositoryImovel) 
        {
            this.repository = repository;
            this.repositoryImovel = repositoryImovel;
        }

        public IActionResult Index()
        {
            var conta = repository.Getall();
            ViewBag.Maximo = repository.Maior();
            ViewBag.Minimo = repository.Menor();
            return View(conta);
        }

        public IActionResult Create()
        {
            ViewBag.ImoveisConta = repositoryImovel.Getall();
            return View();
        }

        [HttpPost]
        public IActionResult Create(Conta conta)
        {
            conta.imovel = repositoryImovel.GetById(conta.imovel.id);
            repository.Create(conta);
            return RedirectToAction("Index");
        }
        public IActionResult Edit(int id)
        {
            ViewBag.ImoveisConta = repositoryImovel.Getall();
            var conta = repository.GetById(id);
            return View(conta);
        }

        [HttpPost]
        public IActionResult Edit(Conta conta)
        {
            conta.imovel = repositoryImovel.GetById(conta.imovel.id);
            repository.Update(conta);
            return RedirectToAction("Index");
        }
        public IActionResult Delete(int id)
        {
            repository.Delete(id);
            return RedirectToAction("Index");
        }
    }
}

ProjetoLuz/ContaWeb/Controllers/HomeController.cs
using System;
using System.Collections.Generic;
using System.Diagnostics;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Mvc;
using ContaWeb.Models;

namespace ContaWeb.Controllers
{
    public class HomeController : Controller
    {
        public IActionResult Index()
        {
            return View();
        }

        public IActionResult Privacy()
        {
            return View();
        }

        [ResponseCache(Duration = 0, Location = ResponseCacheLocation.None, NoStore = true)]
        public IActionResult Error()
        {
            return View(new ErrorViewModel { RequestId = Activity.Current?.Id ?? HttpContext.TraceIdentifier });
        }
    }
}

ProjetoLuz/ContaWeb/Views/Conta/Create.cshtml
@model ContaDomain.Entities.Conta

<div class="form-horizontal">
    <form action="Create" method="Post">

        <div class="form-group">
            <label>Id</label>
            <input  class="form-control"
                    type="text" name="id"/>
        </div>

        <div class="form-group">
            <label>Data Leitura</label>
            <input  class="form-control"
                    type="date" name="dataLeitura"/>
        </div>

        <div class="form-group">
            <label>Numero Leitura</label>
            <input  class="form-control"
                    type="text" name="numeroLeitura"/>
        </div>
        <div class="form-group">
            <label>Quantidade de Kw</label>
            <input  class="form-control"
                    type="text" name="qtdKw"/>
        </div>
        <div class="form-group">
            <label>Valor da Conta</label>
            <input  class="form-control"
                    type="text" name="valorConta"/>
        </div>
        <div class="form-group">
            <label>Data do Pagamento</label>
            <input  class="form-control"
                    type="date" name="dataPagamento"/>
        </div>

        <div class="form-group">
            <label>Media de Consumo</label>
            <input  class="form-control"
                    type="text" name="mediaConsumo"/>
        </div>

        <div class="form-group"> 
            <label for="imovel">Cidade</label>
            <select class="form-control" name="imovel.id" required>
                <option value="" disabled selected>Selecione o Imovel</option>
            @foreach(var imovel in ViewBag.ImoveisConta)
            {
                <option value="@imovel.id">@imovel.id | @imovel.Cidade</option>
            }
            </select>   

        </div>


        <input  class="btn btn-primary" 
                type="submit" value="Salvar"/>

    </form>
</div>

ProjetoLuz/ContaWeb/Views/Conta/Edit.cshtml
@model ContaDomain.Entities.Conta

<div class="form-horizontal">
    <form action="Edit" method="Post">

        <div class="form-group">
            <label>Id</label>
            <input  class="form-control"
                    type="text" name="id"
                    value="@Model.id"/>
        </div>

        <div class="form-group">
            <label>Data Leitura</label>
            <input  class="form-control"
                    type="text" name="dataLeitura"
                    value="@Model.dataLeitura"/>
        </div>

        <div class="form-group">
            <label>Numero Leitura</label>
            <input  class="form-control"
                    type="text" name="numeroLeitura"
                    value="@Model.numeroLeitura"/>
        </div>
        <div class="form-group">
            <label>Quantidade de Kw</label>
            <input  class="form-control"
                    type="text" name="qtdKw"
                    value="@Model.qtdKw"/>
        </div>
        <div class="form-group">
            <label>Valor da Conta</label>
            <input  class="form-control"
                    type="text" name="valorConta"
                    value="@Model.valorConta"/>
        </div>
        <div class="form-group">
            <label>Data do Pagamento</label>
            <input  class="form-control"
                    type="text" name="dataPagamento"
                    value="@Model.dataPagamento"/>
        </div>

        <div class="form-group">
            <label>Media de Consumo</label>
            <input  class="form-control"
                    type="text" name="mediaConsumo"
                    value="@Model.mediaConsumo"/>
        </div>

        <div  class="form-group">
            <label for="imovel">Cidade</label>
            <select class="form-control" name="imovel.id" required>
                    <option value="" disabled>Selecione a Cidade</option>
                @foreach(var imovel in ViewBag.ImoveisConta ){
                    <!option value="@imovel.id" selected="@(@imovel.id == Model.imovel.id)">@imovel.Cidade</!option>
                }
            </select>
        </div>

        <input  class="btn btn-primary" 
                type="submit" value="Salvar"/>

    </form>
</div>

ProjetoLuz/ContaWeb/Views/Conta/Index.cshtml
@model IEnumerable<ContaDomain.Entities.Conta>

    
</br></br>
<a href="Conta/Create" class="btn btn-primary">Nova Conta</a>
</br></br>

<div class="container">
    <table class="table">
        <thead>
            <tr>
                <th>Id</th>
                <th>Data Leitura</th>
                <th>Numero Leitura</th>
                <th>Quantidade Kw</th>
                <th>Valor Conta</th>
                <th>Data Pagamento</th>
                <th>Media de Consumo</th>
                <th>Cidade</th>
                <th></th>
                <th></th>
            </tr>
        </thead>


        @foreach(var item in Model)
        {
            <tr>
                <td>@item.id</td>
                <td>@item.dataLeitura</td>
                <td>@item.numeroLeitura</td>
                <td>@item.qtdKw</td>
                <td>@item.valorConta</td>
                <td>@item.dataPagamento</td>
                <td>@item.mediaConsumo</td>
                <td>@item.imovel.Cidade</td>
                <td><a class="btn btn-danger"
                    href="Conta/Delete/@item.id">Delete</a> </td>
                <td><a class="btn btn-primary" 
                    href="Conta/Edit/@item.id">Editar</a> </td>
            </tr>
        }
    </table>
    <br>
    <hr>  
</div>
        <div class="col-sm-12">
            <h3>Maior Consumo</h3>
            <table class="table table-striped table-bordered">
            <thead>
                <tr>
                    <th>Id</th>
                    <th>Data Leitura</th>
                    <th>Numero Leitura</th>
                    <th>Quantidade Kw</th>
                    <th>Valor Conta</th>
                    <th>Data Pagamento</th>
                    <th>Media de Consumo</th>
                    <th>Cidade</th>
                </tr>
            </thead>
            @if (ViewBag.Maximo != null)
            {

                <tr>
                    <td>@ViewBag.Maximo.id</td>
                    <td>@ViewBag.Maximo.dataLeitura</td>
                    <td>@ViewBag.Maximo.numeroLeitura</td>
                    <td>@ViewBag.Maximo.qtdKw</td>
                    <td>@ViewBag.Maximo.valorConta</td>
                    <td>@ViewBag.Maximo.dataPagamento</td>
                    <td>@ViewBag.Maximo.mediaConsumo</td>
                    <td>@ViewBag.Maximo.imovel.Cidade</td>
                </tr>
                 //your code   
            }
        </table>
        </div>
        <div class="col-sm-12">
            <h3>Menor Consumo</h3>
            <table class="table table-striped table-bordered">
            <thead>
                <tr>
                    <th>Id</th>
                    <th>Data Leitura</th>
                    <th>Numero Leitura</th>
                    <th>Quantidade Kw</th>
                    <th>Valor Conta</th>
                    <th>Data Pagamento</th>
                    <th>Media de Consumo</th>
                    <th>Cidade</th>
                </tr>
            </thead>
                <tr>
                    @if (ViewBag.Minimo != null)
                    {
                    <td>@ViewBag.Minimo.id</td>
                    <td>@ViewBag.Minimo.dataLeitura</td>
                    <td>@ViewBag.Minimo.numeroLeitura</td>
                    <td>@ViewBag.Minimo.qtdKw</td>
                    <td>@ViewBag.Minimo.valorConta</td>
                    <td>@ViewBag.Minimo.dataPagamento</td>
                    <td>@ViewBag.Minimo.mediaConsumo</td>
                    <td>@ViewBag.Minimo.imovel.Cidade</td>
                    }
                </tr>
        </table>
        </div>   
    </div> 
</div>

ProjetoLuz/ContaWeb/Views/Contas/Index.cshtml
@model IEnumerable<ContaDomain.Entities.Conta>

    
</br></br>
<a href="Contas/Create" class="btn btn-primary">Nova Conta</a>
</br></br>

<div class="container">
    <table class="table">
        <thead>
            <tr>
                <th>Id</th>
                <th>Data Leitura</th>
                <th>Numero Leitura</th>
                <th>Quantidade Kw</th>
                <th>Valor Conta</th>
                <th>Data Pagamento</th>
                <th>Media de Consumo</th>
                <th></th>
                <th></th>
            </tr>
        </thead>

        @foreach(var item in Model)
        {
            <tr>
                <td>@item.id</td>
                <td>@item.dataLeitura</td>
                <td>@item.numeroLeitura</td>
                <td>@item.qtdKw</td>
                <td>@item.valorConta</td>
                <td>@item.dataPagamento</td>
                <td>@item.mediaConsumo</td>
                <td>@item.imovel.Cidade</td>
                <td><a class="btn btn-danger"
                    href="Contas/Delete/@item.id">Delete</a> </td>
                <td><a class="btn btn-primary" 
                    href="Contas/Edit/@item.id">Editar</a> </td>
            </tr>
        }
    </table>
</div>
<br>
<hr>
    <h3> Maior Consumo </h3>
    <div class="container">
        <table class="table">
            <thead>
                <tr>
                    <th>Id</th>
                    <th>Data Leitura</th>
                    <th>Numero Leitura</th>
                    <th>Quantidade Kw</th>
                    <th>Valor Conta</th>
                    <th>Data Pagamento</th>
                    <th>Media de Consumo</th>
                    <th></th>
                    <th></th>
                </tr>
            </thead>
                <tr>
                    <td>@ViewBag.Maximo.id</td>
                    <td>@ViewBag.Maximo.dataLeitura</td>
                    <td>@ViewBag.Maximo.numeroLeitura</td>
                    <td>@ViewBag.Maximo.qtdKw</td>
                    <td>@ViewBag.Maximo.valorConta</td>
                    <td>@ViewBag.Maximo.dataPagamento</td>
                    <td>@ViewBag.Maximo.mediaConsumo</td>
                    <td>@ViewBag.Maximo.imovel.Cidade</td>
                </tr>
        </table>
    </div>
<br>
<hr>
     <h3> Menor Consumo </h3>
    <div class="container">
        <table class="table">
            <thead>
                <tr>
                    <th>Id</th>
                    <th>Data Leitura</th>
                    <th>Numero Leitura</th>
                    <th>Quantidade Kw</th>
                    <th>Valor Conta</th>
                    <th>Data Pagamento</th>
                    <th>Media de Consumo</th>
                    <th></th>
                    <th></th>
                </tr>
            </thead>
                <tr>
                    <td>@ViewBag.Minimo.id</td>
                    <td>@ViewBag.Minimo.dataLeitura</td>
                    <td>@ViewBag.Minimo.numeroLeitura</td>
                    <td>@ViewBag.Minimo.qtdKw</td>
                    <td>@ViewBag.Minimo.valorConta</td>
                    <td>@ViewBag.Minimo.dataPagamento</td>
                    <td>@ViewBag.Minimo.mediaConsumo</td>
                    <td>@ViewBag.Minimo.imovel.Cidade</td>
                </tr>
        </table>
    </div>

ProjetoLuz/ContaWeb/Views/Home/Index.cshtml
@{
    ViewData["Title"] = "Home Page";
}

<div class="text-center">
    <h1 class="display-4">Welcome</h1>
    <p>Learn about <a href="https://docs.microsoft.com/aspnet/core">building Web apps with ASP.NET Core</a>.</p>
</div>

ProjetoLuz/ContaWeb/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html>
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>@ViewData["Title"] - ContaWeb</title>

    <environment include="Development">
        <link rel="stylesheet" href="~/lib/bootstrap/dist/css/bootstrap.css" />
    </environment>
    <environment exclude="Development">
        <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.3.1/css/bootstrap.min.css"
              asp-fallback-href="~/lib/bootstrap/dist/css/bootstrap.min.css"
              asp-fallback-test-class="sr-only" asp-fallback-test-property="position" asp-fallback-test-value="absolute"
              crossorigin="anonymous"
              integrity="sha384-ggOyR0iXCbMQv3Xipma34MD+dH/1fQ784/j6cY/iJTQUOhcWr7x9JvoRxT2MZw1T"/>
    </environment>
    <link rel="stylesheet" href="~/css/site.css" />
</head>
<body>
    <header>
        <nav class="navbar navbar-expand-sm navbar-toggleable-sm navbar-light bg-white border-bottom box-shadow mb-3">
            <div class="container">
                <a class="navbar-brand" asp-area="" asp-controller="Home" asp-action="Index">ContaWeb</a>
                <button class="navbar-toggler" type="button" data-toggle="collapse" data-target=".navbar-collapse" aria-controls="navbarSupportedContent"
                        aria-expanded="false" aria-label="Toggle navigation">
                    <span class="navbar-toggler-icon"></span>
                </button>
                <div class="navbar-collapse collapse d-sm-inline-flex flex-sm-row-reverse">
                    <ul class="navbar-nav flex-grow-1">
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Home" asp-action="Index">Home</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Conta" asp-action="Index">Conta</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Home" asp-action="Privacy">Privacy</a>
                        </li>
                    </ul>
                </div>
            </div>
        </nav>
    </header>
    <div class="container">
        <partial name="_CookieConsentPartial" />
        <main role="main" class="pb-3">
            @RenderBody()
        </main>
    </div>

    <footer class="border-top footer text-muted">
        <div class="container">
            &copy; 2019 - ContaWeb - <a asp-area="" asp-controller="Home" asp-action="Privacy">Privacy</a>
        </div>
    </footer>

    <environment include="Development">
        <script src="~/lib/jquery/dist/jquery.js"></script>
        <script src="~/lib/bootstrap/dist/js/bootstrap.bundle.js"></script>
    </environment>
    <environment exclude="Development">
        <script src="https://cdnjs.cloudflare.com/ajax/libs/jquery/3.3.1/jquery.min.js"
                asp-fallback-src="~/lib/jquery/dist/jquery.min.js"
                asp-fallback-test="window.jQuery"
                crossorigin="anonymous"
                integrity="sha256-FgpCb/KJQlLNfOu91ta32o/NMZxltwRo8QtmkMRdAu8=">
        </script>
        <script src="https://stackpath.bootstrapcdn.com/bootstrap/4.3.1/js/bootstrap.bundle.min.js"
                asp-fallback-src="~/lib/bootstrap/dist/js/bootstrap.bundle.min.js"
                asp-fallback-test="window.jQuery && window.jQuery.fn && window.jQuery.fn.modal"
                crossorigin="anonymous"
                integrity="sha384-xrRywqdh3PHs8keKZN+8zzc5TX0GRTLCcmivcbNJWm2rs5C8PRhcEn3czEjhAO9o">
        </script>
    </environment>
    <script src="~/js/site.js" asp-append-version="true"></script>

    @RenderSection("Scripts", required: false)
</body>
</html>